In [539]:
#import necessaary libraries for project
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# ML LIBRARIES
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix,classification_report

In [540]:
# Loading the WA_Fn-UseC_-Telco-Customer-Churn.csv Dataset
df = pd.read_csv("WA_Fn-UseC_-Telco-Customer-Churn.csv")
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

**Exploratory Data Analysis**

In [541]:
# Task 1 : Load the dataset and display the first few rows 

df #-->loaded dataset
df.head() #-->default it prints first 5 rows from dataset

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

Dataset is loaded and first few rows are displayed

In [542]:
# 2. Check dataset shape and data types

print(df.shape) #--> returns shape of dataset

print(df.info()) #-->returns information of dataset including type of data

(7043, 21)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB
None

In [543]:
#finding datatypes
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

- Shape of dataset is (7043, 21)
- There are 18 columns with "Object datatype" , 2 columns with "int datatype"  and 1 column with "float datatype"

In [544]:
# Identifying missing columns
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [545]:
# checking for null values using any 

df.isnull().values.any()

np.False_

- No null values are present in the dataset

In [546]:
# Convert the target column (Churn) into numerical format
df["Churn"].unique()
le = LabelEncoder()
df["Churn"] = le.fit_transform(df["Churn"])
df["Churn"]

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7043, dtype: int64

- Converted target Churn column values into numerical format
- 1-True
- 0-False

In [547]:
#Identify categorical and numerical columns
cat = []
num = []
columns = df.columns
for col in columns:
    if df[col].dtype=="object":
        cat.append(col)
    else:
        num.append(col)
print("Categorical Columns are :",cat)
print("Numerical  Columns are :",num)

Categorical Columns are : ['customerID', 'gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod', 'TotalCharges']
Numerical  Columns are : ['SeniorCitizen', 'tenure', 'MonthlyCharges', 'Churn']

- Categorical Columns are : [customerID, gender, Partner, Dependents, PhoneService, MultipleLines, InternetService, OnlineSecurity, OnlineBackup, DeviceProtection, TechSupport, StreamingTV, StreamingMovies, Contract, PaperlessBilling, PaymentMethod, TotalCharges]
- Numerical  Columns are : [SeniorCitizen, tenure, MonthlyCharges, Churn]

**2. Data Preprocessing:**

In [548]:
#Handling  missing values
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

- There are no null values present in the dataset

In [549]:
#- Encode categorical variables
encoders = {}

for col in cat:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le

- Encoded categorical values into Numerical Values using Label Encoder

In [550]:
#dropping customerID column 
df = df.drop("customerID",axis=1)
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,2505,0
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1466,0
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,157,1
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1400,0
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,925,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,2,0,2,0,2,2,2,2,1,1,3,84.80,1597,0
7039,0,0,1,1,72,1,2,1,0,2,2,0,2,2,1,1,1,103.20,5698,0
7040,0,0,1,1,11,0,1,0,2,0,0,0,0,0,0,1,2,29.60,2994,0
7041,1,1,1,0,4,1,2,1,0,0,0,0,0,0,0,1,3,74.40,2660,1
7042,1,0,0,0,66,1,0,1,2,0,2,2,2,2,2,1,0,105.65,5407,0

- CustomerID column is dropped because it does not affect the prediction

In [579]:
#Dropping churn column as it is the target column
X=df.drop("Churn",axis=1)
y=df["Churn"]

In [552]:
print(X.shape)
print(y.shape)

(7043, 19)
(7043,)

- shape of x is 7043 , 19
- shape of y is 7043

In [580]:
# - Split the data into training and testing sets
Xtrain, Xtest, ytrain, ytest =  train_test_split(X,y,test_size=0.2,random_state=42)

In [554]:
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,2505,0
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1466,0
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,157,1
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1400,0
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,925,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,2,0,2,0,2,2,2,2,1,1,3,84.80,1597,0
7039,0,0,1,1,72,1,2,1,0,2,2,0,2,2,1,1,1,103.20,5698,0
7040,0,0,1,1,11,0,1,0,2,0,0,0,0,0,0,1,2,29.60,2994,0
7041,1,1,1,0,4,1,2,1,0,0,0,0,0,0,0,1,3,74.40,2660,1
7042,1,0,0,0,66,1,0,1,2,0,2,2,2,2,2,1,0,105.65,5407,0

In [555]:
#Feature Scaling
scalar = StandardScaler()
scaled_Xtrain = scalar.fit_transform(Xtrain)
scaled_Xtest = scalar.transform(Xtest)

**Supervised Machine Learning Model**

M0del Training using Logistic Regression

In [556]:
#Model training using Logistic Regression
log_reg = LogisticRegression()
log_reg.fit(scaled_Xtrain,ytrain)

LogisticRegression()

In [581]:
#prediction
ypred = log_reg.predict(scaled_Xtest)
ypred

c:\Users\prana\OneDrive\Desktop\churn_prediction\venv\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([1, 1, 0, ..., 0, 0, 1], shape=(1409,))

In [582]:
#Finding training and testing efficiency
print("Training Efficiency : ",log_reg.score(Xtrain,ytrain))
print("Testing Efficiency : ",log_reg.score(Xtest,ytest))

Training Efficiency :  0.7987220447284346
Testing Efficiency :  0.8133427963094393

In [584]:
#Classification Report
print(classification_report(ypred,ytest))

              precision    recall  f1-score   support

           0       0.73      0.90      0.80       839
           1       0.77      0.50      0.61       570

    accuracy                           0.74      1409
   macro avg       0.75      0.70      0.70      1409
weighted avg       0.74      0.74      0.72      1409

**Observation**
- Accuracy - 74
- Training Efficiency - 79
- Testing Efficiency -81
- Hence model is a generalized model

Model training using SVM

In [585]:
#model training using SVM
svm = SVC(kernel="rbf")
svm.fit(Xtrain,ytrain)

SVC()

In [586]:
#Prediction
ypred = svm.predict(Xtest)
ypred

array([0, 0, 0, ..., 0, 0, 0], shape=(1409,))

In [587]:
# Finding training and testing efficiency
print("Training Efficiency : ",svm.score(Xtrain,ytrain))
print("Testing Efficiency : ",svm.score(Xtest,ytest))

Training Efficiency :  0.7344692935747249
Testing Efficiency :  0.7352732434350603

In [588]:
#Classification Report
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.74      1.00      0.85      1036
           1       0.00      0.00      0.00       373

    accuracy                           0.74      1409
   macro avg       0.37      0.50      0.42      1409
weighted avg       0.54      0.74      0.62      1409

c:\Users\prana\OneDrive\Desktop\churn_prediction\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\prana\OneDrive\Desktop\churn_prediction\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
c:\Users\prana\OneDrive\Desktop\churn_prediction\venv\Lib\site-packages\sklearn\metrics\_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

**Observation**
- Accuracy - 74
- Training Efficiency - 73
- Testing Efficiency -73
- Hence model is a generalized model

Model Training Using Decision Tree Classifier

In [589]:
#Model training using DEcisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(Xtrain,ytrain)

DecisionTreeClassifier()

In [590]:
#Prediction
ypred = dtc.predict(Xtest)
ypred

array([1, 0, 0, ..., 0, 0, 1], shape=(1409,))

In [592]:
#Finding training and testing efficiency
print("Training Efficiency : ",dtc.score(Xtrain,ytrain))
print("Testing Efficiency : ",dtc.score(Xtest,ytest))

Training Efficiency :  0.9985800496982605
Testing Efficiency :  0.7217885024840313

In [591]:
#Classification Report
print(classification_report(ypred,ytest))

              precision    recall  f1-score   support

           0       0.81      0.81      0.81      1034
           1       0.48      0.47      0.48       375

    accuracy                           0.72      1409
   macro avg       0.64      0.64      0.64      1409
weighted avg       0.72      0.72      0.72      1409

**Observation**
- Accuracy - 72
- Training Efficiency - 99
- Testing Efficiency -72
- Hence model is a generalized model

**CONCLUSION**
- Three supervised models were trained: Logistic Regression, SVM, and Decision Tree.
- Logistic Regression and SVM achieved the highest accuracy of 74, while Decision Tree achieved 72. 
- Since Logistic Regression provides the same accuracy as SVM with lower computational complexity and better interpretability.
- Hence, **Logistic Regression** is selected as the final model

In [567]:
#Use best performing model in streamlit app
#Best fit model is Logistic Regression

In [568]:

#Model training using Logistic Regression
log_reg = LogisticRegression()
log_reg.fit(Xtrain,ytrain)

c:\Users\prana\OneDrive\Desktop\churn_prediction\venv\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [593]:
#Prediction
ypred = log_reg.predict(Xtest)
ypred

array([1, 0, 0, ..., 0, 0, 0], shape=(1409,))

In [594]:
#Finding Training and testing efficiency
print("Training Efficiency : ",log_reg.score(Xtrain,ytrain))
print("Testing Efficiency : ",log_reg.score(Xtest,ytest))

Training Efficiency :  0.7987220447284346
Testing Efficiency :  0.8133427963094393

In [596]:
#Confusion matrix
confusion_matrix(ypred,ytest)

array([[935, 162],
       [101, 211]])

In [595]:
#Classification Report
print(classification_report(ypred,ytest))

              precision    recall  f1-score   support

           0       0.90      0.85      0.88      1097
           1       0.57      0.68      0.62       312

    accuracy                           0.81      1409
   macro avg       0.73      0.76      0.75      1409
weighted avg       0.83      0.81      0.82      1409

**CONCLUSION**
- Model is trained using LOGISTIC RERGRESSION

In [597]:
#final cleaned and encoded dataset
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,1,0,0,2,0,0,0,0,0,1,2,29.85,2505,0
1,1,0,0,0,34,1,0,0,2,0,2,0,0,0,1,0,3,56.95,1466,0
2,1,0,0,0,2,1,0,0,2,2,0,0,0,0,0,1,3,53.85,157,1
3,1,0,0,0,45,0,1,0,2,0,2,2,0,0,1,0,0,42.30,1400,0
4,0,0,0,0,2,1,0,1,0,0,0,0,0,0,0,1,2,70.70,925,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,2,0,2,0,2,2,2,2,1,1,3,84.80,1597,0
7039,0,0,1,1,72,1,2,1,0,2,2,0,2,2,1,1,1,103.20,5698,0
7040,0,0,1,1,11,0,1,0,2,0,0,0,0,0,0,1,2,29.60,2994,0
7041,1,1,1,0,4,1,2,1,0,0,0,0,0,0,0,1,3,74.40,2660,1
7042,1,0,0,0,66,1,0,1,2,0,2,2,2,2,2,1,0,105.65,5407,0

4. **Streamlit Application**
- Create a simple Streamlit app
- Take user inputs for customer details
- Display churn prediction result (Churn / No Churn

In [574]:
# Serialization using pickle
import pickle
with open("Logistic_model.pkl","wb") as file:
    pickle.dump(log_reg,file)

In [ ]:
# #Encoder serialization using pickle
with open("label_encoder.pkl","wb") as file1:
    pickle.dump(encoders, file1)

In [598]:
#Scalar serialization using pickle
with open("scaler.pkl","wb") as file2:
    pickle.dump(scalar, file2)

In [599]:
#save the cleaned data
df.to_csv("cleaned_data.csv")

In [600]:
#testing the model with new data
new_data=df.iloc[517:518,:-1]
pred = log_reg.predict(new_data)
pred
if pred==0:
    print("NO CHURN")
else:
    print("YES CHURN")

YES CHURN

**FINAL CONCLUSION**
- The Logistic Regression model was selected as the final model due to its stable performance with 74% accuracy indicating good generalization. 
- The trained model, along with the scaler and encoders, was serialized using Pickle for future use. 
- The serialized model is deployed through a Streamlit application to predict customer churn effectively.